### ISSUE TITLE
Twitter:card is required !

### ISSUE THREAD

**Issue by elhampour** [ASP-NET-MVC-Boilerplate/Framework#12]
in TwitterCard.cs file you have written this line of code 

            `if (this.Type != TwitterCardType.Summary)
            {
                stringBuilder.AppendMetaNameContent("twitter:card", this.Type.ToTwitterString());
            }`

and it think this is wrong , because twitter:card meta tag is required.

**Comment by VeXHarbinger** [comment]
I didn't look at the code after the merge yet, but you are correct that it is required [Required Properties](https://github.com/ASP-NET-MVC-Boilerplate/Framework/issues/3)

**Comment by VeXHarbinger** [comment]
I think you need to pull the latest code, it now reads
```
stringBuilder.AppendMetaNameContent("twitter:card", this.Type.ToTwitterString());

            if (!string.IsNullOrEmpty(this.SiteUsername))
            {
                stringBuilder.AppendMetaNameContent("twitter:site", this.SiteUsername);
            }
```

**Comment by elhampour** [comment]
yes your right , i have to pull the latest code.
