### ISSUE TITLE
Expanding the Username & Id Properties of the Twitter Cards

### ISSUE THREAD

**Issue by VeXHarbinger** [ASP-NET-MVC-Boilerplate/Framework#3]
I created this issue to explain the code changes in my branch.  I extended the Twitter Cards to handle either using the Twitter Username e.g. @Microsoft, or Twitter Id for the Website, as well as the Twitter @username of content creator e.g. @RehanSaeedUK. 
I also modified the Validate function using the current list of required fields based upon the Twitter Card Type.  [Tag Mark-up](https://dev.twitter.com/cards/markup).

So the new code-set now handles the "twitter:site", "twitter:site:id", "twitter:creator", and "twitter:creator:id" tags.

I figure that you'll want to review this data before I issue a Pull request.  Also, this should be committed after the other PR about the Depreciated Card Types.
The code changes for my branch are located [here](https://github.com/VeXHarbinger/Framework/tree/ExpandingTwitterUserTags)

| Tag | **Summary** | **Summary Large** | **Player** | **App** |
| --- | --- | --- | --- | --- |
| twitter:card | R | R | R | R |
| twitter:site | R | R | U | R |
| twitter:site:id | - | U | U | - |
| twitter:creator | - | U | - | - |
| twitter:creator:id | U | U | - | - |
| twitter:description | R | R | U | U |
| twitter:title | R | R | R | - |
| twitter:image | U | U | R | - |
| twitter:image:alt | U | U | R* | - |
| twitter:player | - | - | R | - |
| twitter:player:width | - | - | R | - |
| twitter:player:height | - | - | R | - |
| twitter:player:stream | - | - | U | - |
| twitter:app:name:iphone | - | - | - | U |
| twitter:app:id:iphone | - | - | - | R |
| twitter:app:url:iphone | - | - | - | U |
| twitter:app:name:ipad | - | - | - | U |
| twitter:app:id:ipad | - | - | - | R |
| twitter:app:name:googleplay | - | - | - | R |
| twitter:app:id:googleplay | - | - | - | R |
| twitter:app:url:googleplay | - | - | - | U |

R = Required
U = Usable
R\* = Required, If the streamUrl is provided.

**Comment by VeXHarbinger** [comment]
I have the MVC6 Testing and Validation updated with the expanded cards.
I just have to complete the MVC5 testing and it should be ready to move forwards.  I may have gone a bit overboard with the tests, but I suppose better safe than sorry.

**Comment by RehanSaeed** [comment]
Any updates on the next PR?

**Comment by VeXHarbinger** [comment]
I made it maybe a week or two ago. [https://github.com/ASP-NET-MVC-Boilerplate/Framework/pull/11](url)

**Comment by RehanSaeed** [comment]
The second PR is merged. Can this issue now be closed? I'll arrange a release soon.

**Comment by VeXHarbinger** [comment]
If this is in and the Tests are green we are good to go!

**Comment by RehanSaeed** [comment]
Have pushed a Git tag, the [NuGet](https://www.nuget.org/packages/Boilerplate.AspNetCore.TagHelpers/) package should be pushed shortly.
